<?php

namespace AppBundle\Repository;

/**
 * JouetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JouetRepository extends \Doctrine\ORM\EntityRepository
{
}
