<?php

namespace AppBundle\Repository;

/**
 * JouetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JouetsRepository extends \Doctrine\ORM\EntityRepository
{
}
